version: '3'

services:
  backend:
    build: ./Backend
    container_name: fastapi_app
    restart: always
    ports:
      - "${API_PORT:-8001}:8000"
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-database}
      - REDIS_URL=redis://redis:6379
      - POSTGRES_DB=${POSTGRES_DB:-database}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SMTP_USER=${SMTP_USER:-andres.roblesgilcandas@gmail.com}
      - SMTP_PASS=${SMTP_PASS:-gefl givw felu mess}
      - BASE_URL=https://${DOMAIN_NAME}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - FRONTEND_URL=https://${DOMAIN_NAME}
    networks:
      - fairshare_network
    volumes:
      - ./Backend:/app

  frontend:
    build:
      context: ./Frontend
      args:
        - REACT_APP_API_BASE_URL=http://localhost:8001
    container_name: react_app
    ports:
      - "${FRONTEND_PORT:-3001}:80"
    depends_on:
      - backend
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - DOMAIN_NAME=${DOMAIN_NAME:-fairshare.andresroblesgil.com}
      - API_PORT=${API_PORT:-8001}
    networks:
      - fairshare_network
    #volumes:
    #  - ./Frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "${REDIS_PORT:-6380}:6379"
    networks:
      - fairshare_network

  db:
    image: postgres:15
    container_name: postgres_local
    restart: always
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-database}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./migration:/docker-entrypoint-initdb.d
    networks:
      - fairshare_network

networks:
  fairshare_network:
    driver: bridge

volumes:
  pg_data:
