"""Add date column to expenses

Revision ID: 01344513844c
Revises: 7e2a7a0121c5
Create Date: 2025-03-11 18:24:57.874258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01344513844c'
down_revision: Union[str, None] = '7e2a7a0121c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'date')
    # ### end Alembic commands ###
