"""Add email column to users table

Revision ID: 2f02cbd1ca4a
Revises: f7c3f8a758b0
Create Date: 2025-02-20 18:04:08.722681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f02cbd1ca4a'
down_revision: Union[str, None] = 'f7c3f8a758b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
