"""add_indexes_to_tables

Revision ID: 6a2977b2f98c
Revises: fcf8d1689bee
Create Date: 2025-03-24 19:27:05.819261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a2977b2f98c'
down_revision: Union[str, None] = 'fcf8d1689bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_expense_installment', 'expenses', ['is_installment'], unique=False)
    op.create_index('idx_expense_recurring', 'expenses', ['is_recurring'], unique=False)
    op.create_index('idx_expense_type', 'expenses', ['type'], unique=False)
    op.create_index('idx_expense_user_date', 'expenses', ['user_id', 'date'], unique=False)
    op.create_index('idx_installment_dates', 'installment_expenses', ['begin_date', 'end_date'], unique=False)
    op.create_index('idx_installment_user_active', 'installment_expenses', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_label_user_name', 'labels', ['user_id', 'name'], unique=False)
    op.create_index('idx_recurring_created', 'recurring_expenses', ['created_at'], unique=False)
    op.create_index('idx_recurring_user_active', 'recurring_expenses', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_recurring_user_active', table_name='recurring_expenses')
    op.drop_index('idx_recurring_created', table_name='recurring_expenses')
    op.drop_index('idx_label_user_name', table_name='labels')
    op.drop_index('idx_installment_user_active', table_name='installment_expenses')
    op.drop_index('idx_installment_dates', table_name='installment_expenses')
    op.drop_index('idx_expense_user_date', table_name='expenses')
    op.drop_index('idx_expense_type', table_name='expenses')
    op.drop_index('idx_expense_recurring', table_name='expenses')
    op.drop_index('idx_expense_installment', table_name='expenses')
    # ### end Alembic commands ###
