"""Added labels column to expenses

Revision ID: 6e546afdc0c5
Revises: df4242ac5d55
Create Date: 2025-03-11 19:09:53.951082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e546afdc0c5'
down_revision: Union[str, None] = 'df4242ac5d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('labels', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'labels')
    # ### end Alembic commands ###
