"""Added date fields to InstallmentExpense

Revision ID: cac3ff741d40
Revises: 871c49a82299
Create Date: 2025-03-19 17:34:23.412355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac3ff741d40'
down_revision: Union[str, None] = '871c49a82299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installment_expenses', sa.Column('begin_date', sa.Date(), nullable=False))
    op.add_column('installment_expenses', sa.Column('end_date', sa.Date(), nullable=True))
    op.drop_column('installment_expenses', 'completed_installments')
    op.drop_column('installment_expenses', 'num_installments')
    op.drop_column('installment_expenses', 'completion_percentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installment_expenses', sa.Column('completion_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('installment_expenses', sa.Column('num_installments', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('installment_expenses', sa.Column('completed_installments', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('installment_expenses', 'end_date')
    op.drop_column('installment_expenses', 'begin_date')
    # ### end Alembic commands ###
