"""add num_installments to installment expenses

Revision ID: d40f0480abff
Revises: cac3ff741d40
Create Date: 2025-03-21 21:14:44.358922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40f0480abff'
down_revision: Union[str, None] = 'cac3ff741d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installment_expenses', sa.Column('num_installments', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installment_expenses', 'num_installments')
    # ### end Alembic commands ###
