"""Added relationship between Expense and User

Revision ID: df4242ac5d55
Revises: 62dffc3ea912
Create Date: 2025-03-11 19:02:42.658245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4242ac5d55'
down_revision: Union[str, None] = '62dffc3ea912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('expenses', 'is_installment',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'is_installment',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('expenses', 'is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
