"""add shared sequence for expenses

Revision ID: fcf8d1689bee
Revises: f94f70c4a650
Create Date: 2025-03-23 20:15:24.212999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf8d1689bee'
down_revision: Union[str, None] = 'f94f70c4a650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
